services:
  mysql:
    image: mysql
    volumes: 
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Base_ADBD

  big-data-api:
    image: big-data-api:1.0.0
    ports:
      - "5000:5000"
    restart: always
    environment:
      DATABASE: Base_ADBD
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: admin

volumes:
  db:
    driver: local